// export const ADD_BOATTYPE = "ADD_BOATTYPE";
export const GET_ALLBOATTYPES = "GET_ALLBOATTYPES";
// export const ADD_BOATBRAND = "ADD_BOATBRAND";
export const GET_ALLBOATBRANDS = "GET_ALLBOATBRANDS";
export const GET_ENGINESCOUNT = "GET_ENGINESCOUNT";
export const GET_POWERS = "GET_POWERS";
export const GET_CAPACITY = "GET_CAPACITY";
export const GET_CABINSCOUNT = "GET_CABINSCOUNT";
